### ISSUE TITLE
NodeJS 6.10?

### ISSUE THREAD

**Issue by haraldkubota** [sirceljm/aws-lambda-blog#13]
Hi,

I don know how long AWS will support NodeJS 4.x, but it makes me a bit nervous to depend on something like this for a blog which will possibly live longer. Any plans to move to NodeJS 6.10 (or 8.x when AWS supports it)?

Harald

**Comment by sirceljm** [comment]
I see the node4.3 is still in the install scripts. It this there because at the time this was the highest node version available on aws lambda. I think you can just change it to node6.10 and it should work. 

I should do a little more maintaining of this project. Currenty I am on vacation but will take a look at it when I come back. Otherwise I am working on a similar project to this one which is more developer oriented but still runs on very similar stack. So stay tuned :)

**Comment by haraldkubota** [comment]
I'll try to change to Node 6.10, but there's no urgency as long as 4.3 is still available. I'm glad you did not reply "This does not work on 6.10" 
I'm curious about this "similar project"!

**Comment by haraldkubota** [comment]
FYI: I changed for all Lambda functions: Runtime: "nodejs6.10" (instead of 4.3) and MemorySize: 256 (instead of 512MB) and all is working well as far as I can see.

Unrelated: I also used UglifyJSPlugin for WebPack to reduce the size of the Lambda functions. Not sure I done that right (not much of a front-end person here), but it cut down the Lambda function size from 40k lines to less than 3k and it still works.

No patch or pull request as I'm in the middle of deconstructing the install_advanced.js script to be able to be more update-friendly. The original version works well for one-time installs, but it's overly complex to update a single Lambda function (e.g. the About function).
